language: r
warnings_are_errors: false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - libv8-dev
      
# whitelist
branches:
  only:
    - master
